### ISSUE TITLE
Need more information about seasonal SVR

### ISSUE THREAD

**Issue by kusumy** [gakhov/pycon-ua-2018#1]
Hi, 
First, it is a great article for a beginner like me.
I have an interest in time series forecasting using SVR. 
And your code help me a lot to learn SVR.

I have question about your code, about "Convert observations into the seasonal learning data".
Can you give more information about that code ?

Regards

**Comment by gakhov** [comment]
Hello @kusumy 

We need to transform a timeseries into a number of s-dimentional vectors that represent the seasonally grouped data points. If you have a question about how the grouping of points in a time-series has been done, carefully read the [`build_seasonal_learning_sequences`](https://github.com/gakhov/pycon-ua-2018/blob/master/support-vector-machines.ipynb) function's implementation. If you have problems with understanding the code, probably it is useful to learn more about NumPy (https://numpy.org/doc/stable/)

If you wonder why we actually need to "group" data from a season together, check the [slides](https://github.com/gakhov/pycon-ua-2018/blob/master/slides/gakhov-time-series-forecasting-with-python.pdf) (particularly the slide "How to build a model" in the SVR section) and the usage of the SVR in [sckit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html?highlight=svr#sklearn.svm.SVR)

best,
Andrii
